# Generated by Django 2.2.26 on 2022-06-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComercioApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='nombre',
        ),
    ]
