# Generated by Django 2.2.26 on 2022-07-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComercioApp', '0003_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.CharField(max_length=400),
        ),
    ]
