# Generated by Django 4.0.5 on 2022-07-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComercioApp', '0002_remove_producto_nombre'),
        ('ComercioApp', '0004_auto_20220706_1548'),
    ]

    operations = [
    ]
